development:
  url: <%= ENV['DATABASE_URL'] %>
  adapter: postgres
  database: sinatra_development
  host: localhost
  user: postgres
  password: postgres

test:
  url: <%= ENV['DATABASE_URL'] %>
  adapter: postgres
  database: sinatra_test
  host: localhost
  user: postgres
  password: postgres

production:
  url: <%= ENV['DATABASE_URL'] %>
  adapter: postgres
  database: sinatra_prod
  host: prod-db-host
  user: postgres
  password: postgres
